import { createVenueFixtureFromDataSource } from "./data-source.js";
import {
  SUPPORTED_EVENT_PHASES,
  type VenueDataSource,
  type VenueFixture,
} from "./types.js";

export const localDevelopmentVenueDataSource: VenueDataSource = {
  source: "local-fixture",
  topology: {
    version: "demo-venue-v2",
    venueId: "smart-crowd-demo-venue",
    venueName: "Smart Crowd Demo Venue",
    eventPhases: [...SUPPORTED_EVENT_PHASES],
    nodes: [
      {
        id: "section-a12",
        label: "Section A-12",
        kind: "section",
        zone: "east-lower",
      },
      {
        id: "section-a18",
        label: "Section A-18",
        kind: "section",
        zone: "east-mid",
      },
      {
        id: "section-b08",
        label: "Section B-08",
        kind: "section",
        zone: "center-lower",
      },
      {
        id: "section-c04",
        label: "Section C-04",
        kind: "section",
        zone: "west-lower",
      },
      {
        id: "section-d15",
        label: "Section D-15",
        kind: "section",
        zone: "north-upper",
      },
      {
        id: "concourse-east",
        label: "Concourse East",
        kind: "junction",
        zone: "east",
      },
      {
        id: "concourse-center",
        label: "Concourse Center",
        kind: "junction",
        zone: "center",
      },
      {
        id: "concourse-west",
        label: "Concourse West",
        kind: "junction",
        zone: "west",
      },
      {
        id: "north-ramp",
        label: "North Ramp",
        kind: "junction",
        zone: "north",
      },
      {
        id: "south-ramp",
        label: "South Ramp",
        kind: "junction",
        zone: "south",
      },
      {
        id: "elevator-core",
        label: "Elevator Core",
        kind: "junction",
        zone: "center",
      },
      {
        id: "exit-north-hall",
        label: "North Hall",
        kind: "junction",
        zone: "north",
      },
      {
        id: "exit-south-hall",
        label: "South Hall",
        kind: "junction",
        zone: "south",
      },
      { id: "stall-b", label: "Stall B", kind: "food", zone: "east" },
      { id: "stall-d", label: "Stall D", kind: "food", zone: "west" },
      { id: "stall-f", label: "Stall F", kind: "food", zone: "center" },
      {
        id: "washroom-east",
        label: "Washroom East",
        kind: "washroom",
        zone: "east",
      },
      {
        id: "washroom-west",
        label: "Washroom West",
        kind: "washroom",
        zone: "west",
      },
      {
        id: "family-washroom",
        label: "Family Washroom",
        kind: "washroom",
        zone: "center",
      },
      { id: "gate-east", label: "Gate East", kind: "entry-gate", zone: "east" },
      { id: "gate-west", label: "Gate West", kind: "entry-gate", zone: "west" },
      {
        id: "gate-south",
        label: "Gate South",
        kind: "entry-gate",
        zone: "south",
      },
      { id: "exit-north", label: "Exit North", kind: "exit", zone: "north" },
      { id: "exit-south", label: "Exit South", kind: "exit", zone: "south" },
      { id: "exit-east", label: "Exit East", kind: "exit", zone: "east" },
    ],
    edges: [
      {
        from: "section-a12",
        to: "concourse-east",
        minutes: 2,
        accessible: true,
        congestionPenalty: 1,
        pathType: "concourse",
      },
      {
        from: "section-a18",
        to: "north-ramp",
        minutes: 2,
        accessible: true,
        congestionPenalty: 1,
        pathType: "ramp",
      },
      {
        from: "section-b08",
        to: "concourse-center",
        minutes: 2,
        accessible: true,
        congestionPenalty: 1,
        pathType: "concourse",
      },
      {
        from: "section-c04",
        to: "concourse-west",
        minutes: 2,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "section-d15",
        to: "north-ramp",
        minutes: 3,
        accessible: true,
        congestionPenalty: 1,
        pathType: "ramp",
      },
      {
        from: "section-d15",
        to: "concourse-center",
        minutes: 2,
        accessible: false,
        congestionPenalty: 0,
        pathType: "stairs",
      },
      {
        from: "concourse-east",
        to: "concourse-center",
        minutes: 2,
        accessible: true,
        congestionPenalty: 1,
        pathType: "concourse",
      },
      {
        from: "concourse-center",
        to: "concourse-west",
        minutes: 2,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "concourse-center",
        to: "north-ramp",
        minutes: 2,
        accessible: true,
        congestionPenalty: 1,
        pathType: "ramp",
      },
      {
        from: "concourse-center",
        to: "south-ramp",
        minutes: 2,
        accessible: true,
        congestionPenalty: 0,
        pathType: "ramp",
      },
      {
        from: "concourse-center",
        to: "elevator-core",
        minutes: 1,
        accessible: true,
        congestionPenalty: 1,
        pathType: "elevator",
      },
      {
        from: "concourse-center",
        to: "exit-north-hall",
        minutes: 1,
        accessible: true,
        congestionPenalty: 1,
        pathType: "concourse",
      },
      {
        from: "concourse-center",
        to: "exit-south-hall",
        minutes: 1,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "concourse-east",
        to: "stall-b",
        minutes: 1,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "concourse-west",
        to: "stall-d",
        minutes: 1,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "concourse-center",
        to: "stall-f",
        minutes: 1,
        accessible: true,
        congestionPenalty: 1,
        pathType: "concourse",
      },
      {
        from: "concourse-east",
        to: "washroom-east",
        minutes: 1,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "concourse-west",
        to: "washroom-west",
        minutes: 1,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "elevator-core",
        to: "family-washroom",
        minutes: 1,
        accessible: true,
        congestionPenalty: 0,
        pathType: "elevator",
      },
      {
        from: "concourse-east",
        to: "gate-east",
        minutes: 2,
        accessible: true,
        congestionPenalty: 1,
        pathType: "concourse",
      },
      {
        from: "concourse-west",
        to: "gate-west",
        minutes: 2,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "south-ramp",
        to: "gate-south",
        minutes: 2,
        accessible: true,
        congestionPenalty: 1,
        pathType: "ramp",
      },
      {
        from: "exit-north-hall",
        to: "exit-north",
        minutes: 1,
        accessible: true,
        congestionPenalty: 1,
        pathType: "concourse",
      },
      {
        from: "exit-south-hall",
        to: "exit-south",
        minutes: 1,
        accessible: true,
        congestionPenalty: 0,
        pathType: "concourse",
      },
      {
        from: "concourse-east",
        to: "exit-east",
        minutes: 2,
        accessible: true,
        congestionPenalty: 1,
        pathType: "concourse",
      },
      {
        from: "concourse-east",
        to: "exit-north-hall",
        minutes: 1,
        accessible: false,
        congestionPenalty: 0,
        pathType: "stairs",
      },
    ],
  },
  state: {
    version: "demo-venue-v2-state",
    destinationStates: [
      {
        nodeId: "stall-b",
        status: "open",
        queueMinutes: 8,
        crowdPenalty: 1,
        queueTrendAfterFiveMinutes: -8,
        serviceMinutesPerAdditionalPerson: 2,
        telemetryConfidence: "observed",
        waitTimeVariability: 1,
      },
      {
        nodeId: "stall-d",
        status: "open",
        queueMinutes: 9,
        crowdPenalty: 0,
        queueTrendAfterFiveMinutes: -4,
        serviceMinutesPerAdditionalPerson: 0.5,
        telemetryConfidence: "observed",
        waitTimeVariability: 1,
      },
      {
        nodeId: "stall-f",
        status: "limited",
        queueMinutes: 4,
        crowdPenalty: 2,
        queueTrendAfterFiveMinutes: 2,
        serviceMinutesPerAdditionalPerson: 1.25,
        telemetryConfidence: "estimated",
        waitTimeVariability: 3,
      },
      {
        nodeId: "washroom-east",
        status: "open",
        queueMinutes: 7,
        crowdPenalty: 1,
        queueTrendAfterFiveMinutes: -1,
        serviceMinutesPerAdditionalPerson: 0,
        telemetryConfidence: "observed",
        waitTimeVariability: 1,
      },
      {
        nodeId: "washroom-west",
        status: "open",
        queueMinutes: 4,
        crowdPenalty: 1,
        queueTrendAfterFiveMinutes: 1,
        serviceMinutesPerAdditionalPerson: 0,
        telemetryConfidence: "observed",
        waitTimeVariability: 1,
      },
      {
        nodeId: "family-washroom",
        status: "open",
        queueMinutes: 1,
        crowdPenalty: 0,
        queueTrendAfterFiveMinutes: 0,
        serviceMinutesPerAdditionalPerson: 0,
        telemetryConfidence: "observed",
        waitTimeVariability: 0,
      },
      {
        nodeId: "gate-east",
        status: "open",
        queueMinutes: 5,
        crowdPenalty: 1,
        queueTrendAfterFiveMinutes: -1,
        serviceMinutesPerAdditionalPerson: 0.25,
        telemetryConfidence: "observed",
        waitTimeVariability: 1,
      },
      {
        nodeId: "gate-west",
        status: "open",
        queueMinutes: 2,
        crowdPenalty: 0,
        queueTrendAfterFiveMinutes: 0,
        serviceMinutesPerAdditionalPerson: 0.25,
        telemetryConfidence: "observed",
        waitTimeVariability: 1,
      },
      {
        nodeId: "gate-south",
        status: "limited",
        queueMinutes: 6,
        crowdPenalty: 1,
        queueTrendAfterFiveMinutes: -2,
        serviceMinutesPerAdditionalPerson: 0.5,
        telemetryConfidence: "predicted",
        waitTimeVariability: 4,
      },
      {
        nodeId: "exit-north",
        status: "limited",
        queueMinutes: 7,
        crowdPenalty: 2,
        queueTrendAfterFiveMinutes: -2,
        serviceMinutesPerAdditionalPerson: 0,
        telemetryConfidence: "predicted",
        waitTimeVariability: 4,
      },
      {
        nodeId: "exit-south",
        status: "open",
        queueMinutes: 3,
        crowdPenalty: 0,
        queueTrendAfterFiveMinutes: 0,
        serviceMinutesPerAdditionalPerson: 0,
        telemetryConfidence: "observed",
        waitTimeVariability: 1,
      },
      {
        nodeId: "exit-east",
        status: "closed",
        queueMinutes: 0,
        crowdPenalty: 0,
        queueTrendAfterFiveMinutes: 0,
        serviceMinutesPerAdditionalPerson: 0,
        telemetryConfidence: "estimated",
        waitTimeVariability: 0,
      },
    ],
  },
};

export const demoVenueFixture: VenueFixture = createVenueFixtureFromDataSource(
  localDevelopmentVenueDataSource,
);
