import type { VenueFixture } from "./types.js";

export const demoVenueFixture: VenueFixture = {
  version: "demo-venue-v1",
  nodes: [
    { id: "section-a12", label: "Section A-12", kind: "section" },
    { id: "section-c04", label: "Section C-04", kind: "section" },
    { id: "concourse-east", label: "Concourse East", kind: "junction" },
    { id: "concourse-center", label: "Concourse Center", kind: "junction" },
    { id: "concourse-west", label: "Concourse West", kind: "junction" },
    { id: "exit-north-hall", label: "North Hall", kind: "junction" },
    { id: "exit-south-hall", label: "South Hall", kind: "junction" },
    { id: "stall-b", label: "Stall B", kind: "food" },
    { id: "stall-d", label: "Stall D", kind: "food" },
    { id: "washroom-east", label: "Washroom East", kind: "washroom" },
    { id: "washroom-west", label: "Washroom West", kind: "washroom" },
    { id: "gate-east", label: "Gate East", kind: "entry-gate" },
    { id: "gate-west", label: "Gate West", kind: "entry-gate" },
    { id: "exit-north", label: "Exit North", kind: "exit" },
    { id: "exit-south", label: "Exit South", kind: "exit" },
  ],
  edges: [
    {
      from: "section-a12",
      to: "concourse-east",
      minutes: 2,
      accessible: true,
      congestionPenalty: 1,
    },
    {
      from: "section-c04",
      to: "concourse-west",
      minutes: 2,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "concourse-east",
      to: "concourse-center",
      minutes: 2,
      accessible: true,
      congestionPenalty: 1,
    },
    {
      from: "concourse-center",
      to: "concourse-west",
      minutes: 2,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "concourse-center",
      to: "exit-north-hall",
      minutes: 1,
      accessible: true,
      congestionPenalty: 1,
    },
    {
      from: "concourse-center",
      to: "exit-south-hall",
      minutes: 1,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "concourse-east",
      to: "stall-b",
      minutes: 1,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "concourse-west",
      to: "stall-d",
      minutes: 1,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "concourse-east",
      to: "washroom-east",
      minutes: 1,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "concourse-west",
      to: "washroom-west",
      minutes: 1,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "concourse-east",
      to: "gate-east",
      minutes: 2,
      accessible: true,
      congestionPenalty: 1,
    },
    {
      from: "concourse-west",
      to: "gate-west",
      minutes: 2,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "exit-north-hall",
      to: "exit-north",
      minutes: 1,
      accessible: true,
      congestionPenalty: 1,
    },
    {
      from: "exit-south-hall",
      to: "exit-south",
      minutes: 1,
      accessible: true,
      congestionPenalty: 0,
    },
    {
      from: "concourse-east",
      to: "exit-north-hall",
      minutes: 1,
      accessible: false,
      congestionPenalty: 0,
    },
  ],
  destinationStates: [
    {
      nodeId: "stall-b",
      queueMinutes: 8,
      crowdPenalty: 1,
      queueTrendAfterFiveMinutes: -8,
    },
    {
      nodeId: "stall-d",
      queueMinutes: 9,
      crowdPenalty: 0,
      queueTrendAfterFiveMinutes: -4,
    },
    {
      nodeId: "washroom-east",
      queueMinutes: 7,
      crowdPenalty: 1,
      queueTrendAfterFiveMinutes: -1,
    },
    {
      nodeId: "washroom-west",
      queueMinutes: 2,
      crowdPenalty: 0,
      queueTrendAfterFiveMinutes: 1,
    },
    {
      nodeId: "gate-east",
      queueMinutes: 5,
      crowdPenalty: 1,
      queueTrendAfterFiveMinutes: -1,
    },
    {
      nodeId: "gate-west",
      queueMinutes: 2,
      crowdPenalty: 0,
      queueTrendAfterFiveMinutes: 0,
    },
    {
      nodeId: "exit-north",
      queueMinutes: 7,
      crowdPenalty: 2,
      queueTrendAfterFiveMinutes: -2,
    },
    {
      nodeId: "exit-south",
      queueMinutes: 3,
      crowdPenalty: 0,
      queueTrendAfterFiveMinutes: 0,
    },
  ],
};
